name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/setup-nasm@v1
    - name: make
      run: |
        cd free95
        make link
    - uses: actions/upload-artifact@v4
      with:
        name: Kernel
        path: build/bin/
